# Generated by Django 3.2.8 on 2021-11-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_information_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifierCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='verifier_city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.verifiercity'),
            preserve_default=False,
        ),
    ]
